// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV01Iz42fQvK_F3PIxtf7MnRpK8-zivwI',
    appId: '1:780752413638:web:aebedc667b4c021c9408c7',
    messagingSenderId: '780752413638',
    projectId: 'the-netwrok',
    authDomain: 'the-netwrok.firebaseapp.com',
    storageBucket: 'the-netwrok.appspot.com',
    measurementId: 'G-8Z9M0NLRSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw6rAyKGzExbE1fMNrqm9-uWIHWyjVcgE',
    appId: '1:780752413638:android:57c107a74b55b9bc9408c7',
    messagingSenderId: '780752413638',
    projectId: 'the-netwrok',
    storageBucket: 'the-netwrok.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9i3gR2Iw3y6YO5CdYBs86UiRvbaNQjxY',
    appId: '1:780752413638:ios:935f4f1fc15dc85e9408c7',
    messagingSenderId: '780752413638',
    projectId: 'the-netwrok',
    storageBucket: 'the-netwrok.appspot.com',
    iosBundleId: 'com.mosab.thenetwork.theNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9i3gR2Iw3y6YO5CdYBs86UiRvbaNQjxY',
    appId: '1:780752413638:ios:935f4f1fc15dc85e9408c7',
    messagingSenderId: '780752413638',
    projectId: 'the-netwrok',
    storageBucket: 'the-netwrok.appspot.com',
    iosBundleId: 'com.mosab.thenetwork.theNetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV01Iz42fQvK_F3PIxtf7MnRpK8-zivwI',
    appId: '1:780752413638:web:013092974837cef89408c7',
    messagingSenderId: '780752413638',
    projectId: 'the-netwrok',
    authDomain: 'the-netwrok.firebaseapp.com',
    storageBucket: 'the-netwrok.appspot.com',
    measurementId: 'G-RJRDJ04RYR',
  );

}